config/routes.rb
Rails.application.routes.draw do
  get 'posts/hello'
  get 'posts/goodbye'

  resources :posts do
    resources :comments
  end

  root 'posts#hello'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	
	validates :content, :presence => true, :length => { :minimum => 20 }
  validates :title, :presence => true
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  http_basic_authenticate_with name: "admin", password: "admin"
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    redirect_to post_path(@post)
  end

  def comment_params
  	params.require(:comment).permit(:author, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def hello
    @hello = "Hello World!"
  end

  def goodbye
    @goodbye = "Goodbye World!"
  end

  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogging</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<!-- BANNER -->
		<div class="row" id="banner">
			<div id="logo" class="col-md-2">
				<%= image_tag("logo.png", class: 'logo') %>
			</div>
			<div id="title" class="col-md-8">	
				<h1>Blogging Application</h1>
			</div>
			<div id="logo" class="col-md-2">
				<%= image_tag("logo.png", class: 'logo') %>
			</div>
		</div>
		<div class="row">
			<!-- SIDE NAVBAR -->
			<div id="side" class="col-md-2">
				<ul>
					<li><%= link_to "Show Posts", posts_path %></li>
					<li><%= link_to "Hello", posts_hello_path %></li>
					<li><%= link_to "Goodbye", posts_goodbye_path %></li>
					<li><%= link_to 'New Post', new_post_path %></li>
				</ul>
			</div>
			<!-- MAIN CONTENT -->
			<div id="main" class="col-md-10">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/goodbye.html.erb
<h1>Goodbye</h1>
<h2>Time to say <em><%= @goodbye %></em></h2>

<p><%= link_to "Show Posts", posts_path %></p>

app/views/posts/hello.html.erb
<h1>Hello </h1>
<h2>Time to say <em><%= @hello %></em></h2> 

<p><%= link_to "Show Posts", posts_path %></p>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1><hr>



    <% @posts.each do |post| %>
       <h4> <%= post.name %></h4>
       <h3> <%= post.title %> </h3>
       <p> <%= post.content %></p>
        <%= link_to 'Show', post %> |
        <%= link_to 'Edit', edit_post_path(post) %> |
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %><hr>
    <% end %>

app/views/posts/new.html.erb
<h1>New Post</h1><hr>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


  <h3><strong>Name:</strong>
  <%= @post.name %>
  <h3>


<h2>
  <strong>Title:</strong>
  <%= @post.title %>
</h2>

<p>
  <%= @post.content %>
</p>


<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<hr>
<h2>Comments</h2>
<% if @post.comments.length > 0 %>
  <% @post.comments.each do |comment| %>
    <p>
      <b>Author:</b>
      <%= comment.author %>
    </p>

    <p>
      <b>Comment:</b>
      <%= comment.body %>
    </p>
  <% end %>
<% else %>
  <h3>No comments have been posted yet.</h3>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>